<?php
/*
 * implementation of CiviCRM hook
 */
function civicrm_views_token_civicrm_tokens(&$tokens ) {
   $tokens['civicrm_views_tokens'] = array();
   foreach (_civicrm_views_token_get_views() as $view_name) {
     $tokens['civicrm_views_tokens']['civicrm_views_tokens.view' . $view_name] = 'Configured Drupal View ' . $view_name;
   }
}

/*
 * implementation of CiviCRM hook
 */
function civicrm_views_token_civicrm_tokenValues( &$values, &$contactIDs, $jobID ) {
   static $rendered;
   if($rendered) {
     return $rendered;
   }
   $view_names = _civicrm_views_token_get_views();

   foreach ($view_names as $view_name) {
     $view = views_get_view($view_name);
     if($view) {
       $args = array();
       //$rendered[$view_name] = $view->preview('block', $args);
       $rendered[$view_name] = views_embed_view($view_name);
     }
     else {
       // relying on the view name being correct is a breaky point so we will just
       // give an empy response
       $rendered[$view_name] = NULL;
     }
     foreach ($contactIDs as $contactID) {
       $values[$contactID]['civicrm_views_tokens.view' . $view_name] = $rendered[$view_name];
     }
   }
}

/**
 * Get list of configured views - maybe in future we could make them an aspect of the view
 * for now people can set the variable or name their view 'email'
 */
function _civicrm_views_token_get_views() {
  return (array) variable_get('civicrm_views_token_views', array('email'));
}

